DatosMVC/Models/Datos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos
    {
        public int DatosId { get; set; }
        public string Nombre { get; set; }
        public string NumeroTarjeta { get; set; }
        public string NumeroCuenta { get; set; }
        public string Contrasena { get; set; }
        public string DobleContrasena { get; set; }
    }
}

DatosMVC/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatosPersonalesEntities : DbContext
    {
        public DatosPersonalesEntities()
            : base("name=DatosPersonalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Datos> Datos { get; set; }
    }
}

DatosMVC/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\horacio.alaniz.NEORIS\OneDrive - NEORIS\Documents\HoracioAlaniz\Desarrollo\DatosPersonales\DatosMVC\DatosMVC\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

DatosMVC/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

DatosMVC/Controllers/DatosController.cs
using DatosMVC.DAO;
using DatosMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DatosMVC.Controllers
{
    public class DatosController : Controller
    {
        DatosClass datosClass = new DatosClass();
        // GET: Datos
        public ActionResult Index()
        {
            List<Datos> datos = datosClass.Consultar();
            return View(datos);
        }

        public ActionResult Detalles(int id)
        {
            Datos datos = datosClass.Consultar(id);
            return View(datos);
        }

        public ActionResult Guardar()
        {
            return View();
        }

        public ActionResult Nuevo(Datos datos)
        {
            datosClass.Guardar(datos);
            //return View("Guardar", datos);
            return RedirectToAction("Index");
        }

       public ActionResult Editar(int id)
        {
            Datos datos = datosClass.Consultar(id);
            return View(datos);
        }
        public ActionResult Actualizar(Datos datos)
        {
            datosClass.Editar(datos);
            //return View("Editar", datos);
            return RedirectToAction("Index");
        }

        public ActionResult Eliminar(int id)
        {
            Datos datos = datosClass.Consultar(id);
            datosClass.Eliminar(datos);

           List<Datos> list = datosClass.Consultar();
            return View("Index", list);

        }
    }
}

DatosMVC/Controllers/HomeController.cs
using DatosMVC.DAO;
using DatosMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DatosMVC.Controllers
{
    public class HomeController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DatosMVC/Views/Datos/Detalles.cshtml
@model DatosMVC.Models.Datos

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroTarjeta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroTarjeta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroCuenta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroCuenta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contrasena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contrasena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DobleContrasena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DobleContrasena)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.DatosId }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
</p>

DatosMVC/Views/Datos/Editar.cshtml
@model DatosMVC.Models.Datos

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm("Actualizar", "Datos", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DatosId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroTarjeta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroTarjeta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroTarjeta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroCuenta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroCuenta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroCuenta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contrasena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contrasena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contrasena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DobleContrasena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DobleContrasena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DobleContrasena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DatosMVC/Views/Datos/Guardar.cshtml
@model DatosMVC.Models.Datos

@{
    ViewBag.Title = "Guardar";
}

<h2>Alta de tarjetas y contraseñas</h2>


@using (Html.BeginForm("Nuevo","Datos", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroTarjeta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroTarjeta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroTarjeta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroCuenta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroCuenta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroCuenta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contrasena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contrasena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contrasena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DobleContrasena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DobleContrasena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DobleContrasena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index", null ,new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DatosMVC/Views/Datos/Index.cshtml
@model IEnumerable<DatosMVC.Models.Datos>

@{
    ViewBag.Title = "Index";
}

<center><h2>Bienvenido</h2></center>

<p>
    @Html.ActionLink("Nuevo", "Guardar", null, new { @class = "btn btn-primary" })
</p>

<table class="table table-responsive table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumeroTarjeta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumeroCuenta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contrasena)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DobleContrasena)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroTarjeta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroCuenta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contrasena)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DobleContrasena)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.DatosId }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Detalles", "Detalles", null, new { id = item.DatosId }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Eliminar", "Eliminar", null, new { id = item.DatosId }, new { @class = "btn btn-primary" })
            </td>
        </tr>
    }

</table>

DatosMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DatosMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DatosMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Bienvenido!!</h1>
    <p class="lead">Horacio Guadalupe Alaniz Hernández</p>
    <p><a target="_blank" href="https://www.facebook.com/horacioguadalupe.alanizhernandez" class="btn btn-primary btn-lg">Facebook &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        @*<h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>*@
    </div>
    <div class="col-md-4">
        @*<h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>*@
    </div>
    <div class="col-md-4">
        @*<h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>*@
    </div>
</div>

DatosMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bienvenido", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Consulta de contraseñas", "Index", "Datos")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <center><p>&copy; @DateTime.Now.ToString("dd/MM/yyyy") - Horacio Alaniz</p></center>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>